# Adapted from: https://github.com/ready4-dev/ready4class/runs/3657635374?check_suite_focus=true
#
# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          #- {os: windows-latest, r: '3.6'}
#          - {os: ubuntu-20.04,   r: 'devel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest", http-user-agent: "R/4.0.0 (ubuntu-20.04) R (4.0.0 x86_64-pc-linux-gnu x86_64 linux-gnu) on GitHub Actions" }
#          - {os: ubuntu-20.04,   r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
          #- {os: ubuntu-20.04,   r: 'oldrel',  rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3 #
      - uses: r-lib/actions/setup-r@v2
        # with:
        #   r-version: ${{ matrix.config.r }}
        #   http-user-agent: ${{ matrix.config.http-user-agent }}
        #   use-public-rspm: true
      - uses: r-lib/actions/setup-tinytex@v2
      - run: tlmgr --version
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.17.1' # The pandoc version to download (if necessary) and use.
      - run: echo "# Test" | pandoc -t html
        # Addresses issue with incompatibility between libcurl4-gnutls-dev and libcurl4-openssl-dev
        # Below fix is a customisation of approach outlined in https://github.com/r-hub/sysreqsdb/issues/77#issuecomment-620025428
      - name: Install libraptor on Linux
        if: runner.os == 'Linux'
        run: |
          sudo add-apt-repository ppa:cran/librdf
          sudo apt update
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::XML, any::rcmdcheck
          needs: check
      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--as-cran")'
          error-on: '"error"'
          check-dir: '"check"'
